variables:
  PIPELINE_IMAGE: $CI_REGISTRY_IMAGE/pipelines
  MODEL_IMAGE: $CI_REGISTRY_IMAGE/training
  SENTIMENT_IMAGE: $CI_REGISTRY_IMAGE/sentiments

build-pipeline-image:
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - cd src/future-pipeline && docker build -t $PIPELINE_IMAGE .
    - docker push $PIPELINE_IMAGE
  when: manual
  allow_failure: false

build-training-image:
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - cd src/ml && docker build -t $MODEL_IMAGE .
    - docker push $MODEL_IMAGE
  when: manual
  allow_failure: false

build-sentiment-image:
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - cd src/analysis && docker build -t $SENTIMENT_IMAGE .
    - docker push $SENTIMENT_IMAGE
  when: manual
  allow_failure: false